server:
    port:
        8088

spring.application.name: api-gateway-security

zuul:
    routes:
        api-discovery:
            url: http://localhost:8761
        api-customer:
            url: http://localhost:8081
        api-dealer:
            url: http://localhost:8082
        api-delivery:
            url: http://localhost:8083
        api-admin:
            url: http://localhost:8084
        api-product:
            url: http://localhost:8085
        api-order:
            url: http://localhost:8086
        api-cart:
            url: http://localhost:8087
        api-payment:
            url: http://localhost:8089
       
    host:
        connect-timeout-millis: 2000
        socket-timeout-millis: 5000

spring.data.mongodb.uri: mongodb+srv://namanKapoor:nkss2010@namankapoorcluster.itm4q.mongodb.net/ShoppingCartCaseStudy?retryWrites=true&w=majority